### ISSUE TITLE
ensen fails to build

### ISSUE THREAD

**Issue by batden** [dimmus/ensen#2]
Hello dimmus,
I get this error:

$ meson setup build
The Meson build system
Version: 0.61.2
Source dir: /home/batden/Documents/sources/ensen
Build dir: /home/batden/Documents/sources/ensen/build
Build type: native build
Project name: ensen
Project version: 0.1.119
C compiler for the host machine: ccache gcc (gcc 11.3.0 "gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: gcc ld.bfd 2.38
C++ compiler for the host machine: ccache g++ (gcc 11.3.0 "g++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the host machine: g++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -W: YES 
Compiler for C supports arguments -Wshadow: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES 
Compiler for C supports arguments -Wmissing-prototypes: YES 
Compiler for C supports arguments -Wunused-parameter: YES 
Compiler for C supports arguments -Wsign-compare: YES 
Compiler for C supports arguments -Wpointer-arith: YES 
Compiler for C supports arguments -Wno-missing-field-initializers: YES 
Compiler for C supports arguments -Wfloat-equal: YES 
Compiler for C supports arguments -Wuninitialized: YES 
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wendif-labels: YES 
Compiler for C supports arguments -Wcast-align: YES 
Compiler for C supports arguments -Wformat=2: YES 
Compiler for C supports arguments -Wimplicit-fallthrough=2: YES 
Compiler for C supports arguments -Winit-self: YES 
Compiler for C supports arguments -Wlogical-op: YES 
Compiler for C supports arguments -Wmissing-include-dirs: YES 
Compiler for C supports arguments -Wold-style-definition: YES 
Compiler for C supports arguments -Woverflow: YES 
Compiler for C supports arguments -Wstrict-aliasing=2: YES 
Compiler for C supports arguments -Wstrict-prototypes: YES (cached)
Compiler for C supports arguments -fstrict-aliasing: YES 
Compiler for C supports arguments -Wno-format-y2k: YES 
Compiler for C supports arguments -Wno-variadic-macros: YES 
Compiler for C supports arguments -Wno-strict-aliasing: YES 
Compiler for C supports arguments -Wno-format-nonliteral: YES 
Compiler for C supports arguments -Wno-implicit-fallthrough: YES 
Library m found: YES
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency gsl found: YES 2.7.1
Run-time dependency fftw3 found: YES 3.3.8
Program lcov found: YES (/usr/bin/lcov)
Program gnuplot found: YES (/usr/bin/gnuplot)
Program doxygen found: YES (/usr/bin/doxygen)

**meson.build:188:2: ERROR: Non-existent build file 'doc/meson.build'**

Also, you may want to add the following packages to the requirements:
(ligsl-dev)
(libfftw3-dev)
lcov
gnuplot
doxygen

Cheers

**Comment by dimmus** [comment]
Thanks for try.
I'm testing documentation infrastructures, so for now you need to choose 'scdoc' or 'doxygen'. Then make a link to the appropriate folder. For example, for scdoc it should be 'ln -s doc_scd doc'. Unfortunately, git doesn't work with simlinks, so it disappeared after push.

Another way is to turn off documentation build in meson options.

Thanks for the suggestion for requirements. Do it a little bit later.
Code is highly WIP.

**Comment by dimmus** [comment]
Thanks for try.
I'm testing documentation infrastructures, so for now you need to choose 'scdoc' or 'doxygen'. Then make a link to thr appropriate folder. For example, for scdoc it should be 'ln -s doc_scd doc'. Unfortunately, git does't work with simlinks, so it disappeared after push.

Another way is to turn off documentation build in meson options.

Thanks for the suggestion for requirements. Do it a little bit later.
Code is highly WIP.
